# Global Settings
language: en-US
tone_instructions: ""
early_access: false
enable_free_tier: true

# Reviews Configuration
reviews:
  # Review profile mode
  profile: chill  # Options: chill, assertive

  # Workflow settings
  request_changes_workflow: false

  # Summary and title settings
  high_level_summary: true
  high_level_summary_placeholder: "@coderabbitai summary"
  high_level_summary_in_walkthrough: false
  auto_title_placeholder: "@coderabbitai"
  auto_title_instructions: ""

  # Status and reporting
  review_status: true
  commit_status: true
  fail_commit_status: false

  # Display settings
  collapse_walkthrough: false
  changed_files_summary: true
  sequence_diagrams: true
  estimate_code_review_effort: true

  # Issue and PR analysis
  assess_linked_issues: true
  related_issues: true
  related_prs: true

  # Labels and reviewers
  suggested_labels: true
  auto_apply_labels: false
  suggested_reviewers: true
  auto_assign_reviewers: false

  # Fun features
  in_progress_fortune: true
  poem: true

  # Performance settings
  abort_on_close: true
  disable_cache: false

  # Path filters (glob patterns to include/exclude files)
  path_filters: []

  # Automatic review configuration
  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords: []
    labels: []
    drafts: false
    base_branches: []
    ignore_usernames: []

  # Path-specific instructions
  path_instructions: []
  # Example:
  # - path: "src/**.ts"
  #   instructions: "Focus on type safety and error handling"

  # Label-specific instructions
  labeling_instructions: []
  # Example:
  # - label: "security"
  #   instructions: "Check for security vulnerabilities"

  # Finishing touches (auto-generation)
  finishing_touches:
    docstrings:
      enabled: true
    unit_tests:
      enabled: true

  # Pre-merge quality checks
  pre_merge_checks:
    docstrings:
      mode: warning  # Options: off, warning, error
      threshold: 80
    title:
      mode: warning
      requirements: ""
    description:
      mode: warning
    issue_assessment:
      mode: warning
    custom_checks: []
    # Example:
    # - mode: warning
    #   name: "Custom Check"
    #   instructions: "Ensure all functions have unit tests"

  # Static analysis tools
  tools:
    ast-grep:
      enabled: true
      essential_rules: true
      rule_dirs: []
      util_dirs: []
      packages: []
    biome:
      enabled: true
    checkov:
      enabled: true
    clippy:
      enabled: true
    cppcheck:
      enabled: true
    eslint:
      enabled: true
    gitleaks:
      enabled: true
    github-checks:
      enabled: true
      timeout_ms: 90000
    golangci-lint:
      enabled: true
    hadolint:
      enabled: true
    ktlint:
      enabled: true
    languagetool:
      enabled: true
      enabled_rules: []
      disabled_rules: []
      enabled_categories: []
      disabled_categories: []
      enabled_only: false
      level: default
    markdownlint:
      enabled: true
    phpcs:
      enabled: true
    phpstan:
      enabled: true
    pmd:
      enabled: true
    pylint:
      enabled: true
    ruff:
      enabled: true
    rubocop:
      enabled: true
    semgrep:
      enabled: true
    shellcheck:
      enabled: true
    sqlfluff:
      enabled: true
    swiftlint:
      enabled: true
    trivy:
      enabled: true
    yamllint:
      enabled: true

# Chat Configuration
chat:
  art: true
  auto_reply: true
  integrations:
    jira:
      usage: auto  # Options: auto, enabled, disabled
    linear:
      usage: auto  # Options: auto, enabled, disabled

# Knowledge Base Configuration
knowledge_base:
  opt_out: false

  web_search:
    enabled: true

  code_guidelines:
    enabled: true
    filePatterns: []
    # Common patterns are included by default:
    # - .cursorrules
    # - CODING_STANDARDS.md
    # - CONTRIBUTING.md
    # - docs/coding-guidelines.*

  learnings:
    scope: auto  # Options: local, global, auto

  issues:
    scope: auto  # Options: local, global, auto

  pull_requests:
    scope: auto  # Options: local, global, auto

  jira:
    usage: auto
    project_keys: []
    # Example: ["PROJ", "TEAM"]

  linear:
    usage: auto
    team_keys: []
    # Example: ["ENG", "PROD"]

  mcp:
    usage: auto
    disabled_servers: []

# Code Generation Configuration
code_generation:
  docstrings:
    language: en-US
    path_instructions: []
    # Example:
    # - path: "src/**.py"
    #   instructions: "Use Google-style docstrings"

  unit_tests:
    path_instructions: []
    # Example:
    # - path: "src/**.ts"
    #   instructions: "Use Jest for testing with describe/it blocks"
